### ISSUE TITLE
Inconsistent use of 'V' value prefix

### ISSUE THREAD

**Issue by daveshah1** [SymbiFlow/prjuray#9]
Most of the 1/0 choices in https://github.com/SymbiFlow/prjuray-db/blob/master/zynqusp/segbits_clem.db use `.V1`/`.V0` to distinguish value possibilities.

e.g.
```
CLEM.ABCDFF.CEUSED.V0 !14_07
CLEM.ABCDFF.CEUSED.V1 14_07
CLEM.ABCDFF.CLKINV.V0 !08_19
CLEM.ABCDFF.CLKINV.V1 08_19
CLEM.AFF.INIT.V0 12_02
CLEM.AFF.INIT.V1 !12_02
```

but WA[789]USED seems to be an exception:

```
CLEM.WA7USED.0 !08_23
CLEM.WA7USED.1 08_23
CLEM.WA8USED.0 !11_22
CLEM.WA8USED.1 11_22
CLEM.WA9USED.0 !09_22
CLEM.WA9USED.1 09_22
```

It would simplify things generating/parsing FASM if one convention could be established here (I personally don't mind either way.)

**Comment by litghost** [comment]
This is a bug, I"ll submit a fix today.
